public with sharing class SystemJSONGeneratorService {
    public SystemJSONGeneratorService() {

    }

//     JSONGenerator jsonGenerator = JSON.createGenerator(true);
// jsonGenerator.writeStartArray();
// jsonGenerator.writeStartObject();
// jsonGenerator.writeBooleanField('isStatus',true);
// jsonGenerator.writeEndObject();    
// jsonGenerator.writeEndArray();
// jsonGenerator.close();
// System.debug(jsonGenerator.getAsString());
}
